### ISSUE TITLE
Error: Alfred preferences not found at location /Users/username/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist

### ISSUE THREAD

**Issue by mitchkramez** [importre/alfred-brightness#2]
alfy-init is throwing this error, even though the file does exist at this path, and i can open it:

```
> alfred-brightness@1.0.0 postinstall /usr/local/lib/node_modules/alfred-brightness
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/username/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-brightness/node_modules/resolve-alfred-prefs/index.js:15:10)
    at <anonymous>

    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-brightness/node_modules/execa/index.js:201:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/username/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-brightness/node_modules/resolve-alfred-prefs/index.js:15:10)\n    at <anonymous>\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
```

**Comment by importre** [comment]
Please refer to https://github.com/importre/alfred-slack-status/issues/2
